---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game-deployment
  namespace : game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-game
  template: 
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-container
        image: kagesh4u/myrepo:myweb
        ## image: thipparthiavinash/2048-game
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace : game-2048
spec:
  selector:
    app: 2048-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

